export const SAVE_SHIPPING_USER_INFO = 'SAVE_SHIPPING_USER_INFO';
export const SAVE_DELIVERY_INFO = 'SAVE_DELIVERY_INFO';
export const SUCCESS_SAVE_DELIVERY_INFO = 'SUCCESS_SAVE_DELIVERY_INFO';
export const FAILED_SAVE_DELIVERY_INFO = 'FAILED_SAVE_DELIVERY_INFO';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
